apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  type: ClusterIP
  selector:
    app: minio
  ports:
  - port: 9000
    name: server
    targetPort: server
  - port: 9001
    name: console
    targetPort: console
---
apiVersion: v1
kind: Service
metadata:
  name: minio-headless
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: minio
  ports:
  - port: 9000
    targetPort: server
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
spec:
  selector:
    matchLabels:
      app: minio
  serviceName: minio-headless
  replicas: 1
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: server
        image: quay.io/minio/minio:latest
        args: ['server', '/data', '--console-address', ':9001']
        env:
          - name: MINIO_ROOT_USER
            value: miniouser
          - name: MINIO_ROOT_PASSWORD
            value: miniopassword
        ports:
        - containerPort: 9000
          name: server
        - containerPort: 9001
          name: console
        volumeMounts:
        - name: minio-data
          mountPath: /data
      # volumes:
      #   - name: minio-data-dev
      #     emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: minio-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
