apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        imagePullPolicy: Never
        image: worker:0.1
        resources:
          limits:
            memory: "4Gi"
            cpu: "1"
